# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'noci')"
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          export UV_TORCH_BACKEND=cpu 
          uv pip install -e '.[test,pkaani]'
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check . --config=ruff_essential.toml --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          ruff check . --exit-zero --statistics
      - name: Test with pytest and coverage
        run: |
          coverage run -m pytest
          coverage report -m | tee coverage.txt
          coverage html
      - name: Upload coverage results
        run: bash <(curl -s https://codecov.io/bash)
      - name: Store coverage text results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-text-my-${{ matrix.python-version }}
          path: coverage.txt
      - name: Store coverage HTML results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.python-version }}
          path: htmlcov/*
